version: 0.0
os: linux
files:
  - source: application
    destination: /home/bitnami/kastor_customize
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
